 
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_clinica
    environment:
      SA_PASSWORD: "Password123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  api:
    build:
      context: ./Server
      dockerfile: ProyectoClinica.Server/Dockerfile
    container_name: api_clinica
    ports:
      - "8080"
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=ClinicaDB;User=sa;Password=Password123!;TrustServerCertificate=True"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_clinica
    ports:
      - "80"
    depends_on:
      - api

  nginx:
    image: nginx:latest
    container_name: nginx_clinica
    ports: 
      - "80:80"
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      -  frontend
      -  api


volumes:
  sql_data:
